# Generated by Django 6.0.4 on 2026-04-30 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(editable=False, max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidats/')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('poste_recherche', models.CharField(choices=[('FEMME_DE_MENAGE', 'Femme de ménage'), ('NOUNOU', 'Nounou'), ('VENDEUSE', 'Vendeuse'), ('CUISINIERE', 'Cuisinière')], max_length=50)),
                ('experience', models.TextField()),
                ('disponibilite', models.CharField(choices=[('DAILY', 'Tous les jours'), ('BI_WEEKLY', 'Descend chaque 15 jours'), ('LIVE_IN', 'Logée'), ('LIVE_OUT', 'Non logée')], max_length=50)),
                ('statut', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('PLACED', 'Placé'), ('WAITING', 'En attente')], default='AVAILABLE', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu_travail', models.CharField(max_length=255)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateField()),
                ('statut_emploi', models.CharField(choices=[('ACTIVE', 'En poste'), ('LEFT', 'A quitté le poste')], default='ACTIVE', max_length=20)),
                ('est_paye', models.BooleanField(default=False, verbose_name='Frais payés')),
                ('date_placement', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='management.candidat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='management.client')),
            ],
            options={
                'verbose_name': 'Placement',
                'verbose_name_plural': 'Placements',
            },
        ),
    ]
