# Generated by Django 6.0.4 on 2026-04-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Frais de l'agence", max_digits=10),
        ),
    ]
