# Generated by Django 6.0.4 on 2026-04-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_placement_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='piece_identite',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name="Pièce d'identité (Scan/Photo)"),
        ),
        migrations.AddField(
            model_name='placement',
            name='date_paiement',
            field=models.DateField(blank=True, null=True, verbose_name='Date de réception du paiement'),
        ),
    ]
