# Generated by Django 6.0.4 on 2026-04-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_candidat_piece_identite_placement_date_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin de contrat'),
        ),
    ]
