# Generated by Django 6.0.4 on 2026-04-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_placement_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='certificat_medical',
            field=models.FileField(blank=True, null=True, upload_to='documents/sante/', verbose_name='Certificat Médical'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='piece_identite',
            field=models.FileField(blank=True, null=True, upload_to='documents/cni/', verbose_name="Carte d'Identité (PDF/Image)"),
        ),
    ]
