# Generated by Django 6.0.4 on 2026-05-01 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('LOYER', 'Loyer'), ('SALAIRE', 'Salaires Staff'), ('INTERNET', 'Internet & Tel'), ('MARKETING', 'Publicité'), ('AUTRE', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_depense', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense'],
            },
        ),
    ]
