# Generated by Django 6.0.4 on 2026-05-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='disponibilite',
            field=models.CharField(choices=[('DAILY', 'Tous les jours'), ('BI_WEEKLY', 'Descend chaque 15 jours'), ('WEEKLY_SAT', 'Descend chaque samedi'), ('EVERY_DAY', 'Descend chaque jour'), ('LIVE_IN', 'Logée'), ('LIVE_OUT', 'Non logée')], max_length=50),
        ),
    ]
