# Generated by Django 6.0.4 on 2026-05-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_candidat_disponibilite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('poste_recherche', models.CharField(choices=[('MENAGE', 'Femme de ménage'), ('NOUNOU', 'Nounou garde enfant'), ('CUISINE_PRO', 'Cuisinière professionnel'), ('CUISINE_SEN', 'Cuisinière plat sénégalais'), ('BOY', 'Boy domestique'), ('NET_BUREAU', 'Nettoyage bureau'), ('NET_3J', 'Nettoyage 3 jour dans la semaine'), ('NET_ESCALIER', 'Nettoyage escalier'), ('NET_APPART', 'Nettoyage appartement'), ('NET_CHANTIER', 'Nettoyage fin de chantier'), ('NET_SOIR', 'Nettoyage soir'), ('NET_RESTO', 'Nettoyage restaurant'), ('VENDEUSE', 'Vendeuse Boutique'), ('CAISSIER', 'Caissière (er)'), ('SERVEUR', 'Serveuse (er)'), ('CHAUFFEUR_P', 'Chauffeur particulier'), ('CHAUFFEUR_Y', 'Chauffeur yango'), ('LIVREUR_MOTO', 'Chauffeur livreur moto'), ('GARDIEN', 'Gardiennage jour ou nuit'), ('AIDE_VIE', 'Aide personne âgée'), ('GOUVERNANTE', 'Gouvernante'), ('CUISINE_NET', 'Cuisine et nettoyage appartement'), ('JARDINIER', 'Jardinier'), ('SECRETAIRE', 'Secrétaire'), ('ASSISTANTE', 'Assistante'), ('PLONGE', 'Plongé Restaurant'), ('LINGERE', 'Lingère et repassage'), ('AUTRE', 'Autre.....')], max_length=50)),
                ('quartier', models.CharField(max_length=100)),
                ('budget_max', models.DecimalField(decimal_places=0, help_text='Budget mensuel (FCFA)', max_digits=10)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('est_traitee', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
    ]
