# Generated by Django 6.0.4 on 2026-05-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_clientrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='disponibilite',
            field=models.CharField(choices=[('JOURNALIER', 'Journalier'), ('WEEKLY', 'Descente chaque semaine'), ('BI_WEEKLY', 'Descend chaque 15 jours'), ('LIVE_IN', 'Logée'), ('LIVE_OUT', 'Non logée')], max_length=50),
        ),
    ]
