# Generated by Django 6.0.4 on 2026-05-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_candidat_disponibilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='poste_recherche',
            field=models.CharField(choices=[('MENAGE', 'Femme de ménage'), ('NOUNOU', 'Nounou garde enfant'), ('CUISINE_PRO', 'Cuisinière professionnel'), ('CUISINE_SEN', 'Cuisinière plat sénégalais'), ('BOY', 'Boy domestique'), ('NET_BUREAU', 'Nettoyage bureau'), ('NET_3J', 'Nettoyage 3 jour dans la semaine'), ('NET_ESCALIER', 'Nettoyage escalier'), ('NET_APPART', 'Nettoyage appartement'), ('NET_CHANTIER', 'Nettoyage fin de chantier'), ('NET_SOIR', 'Nettoyage soir'), ('NET_RESTO', 'Nettoyage restaurant'), ('VENDEUSE', 'Vendeuse Boutique'), ('CAISSIER', 'Caissière (er)'), ('SERVEUR', 'Serveuse (er)'), ('CHAUFFEUR_P', 'Chauffeur particulier'), ('CHAUFFEUR_Y', 'Chauffeur yango'), ('LIVREUR_MOTO', 'Chauffeur livreur moto'), ('GARDIEN', 'Gardiennage jour ou nuit'), ('AIDE_VIE', 'Aide personne âgée'), ('GOUVERNANTE', 'Gouvernante'), ('CUISINE_NET', 'Cuisine et nettoyage appartement'), ('JARDINIER', 'Jardinier'), ('SECRETAIRE', 'Secrétaire'), ('ASSISTANTE', 'Assistante'), ('PLONGE', 'Plongé Restaurant'), ('LINGERE', 'Lingère et repassage'), ('AUTRE', 'Autre.....')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='statut',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('PLACED', 'Placé'), ('WAITING', 'En attente')], db_index=True, default='AVAILABLE', max_length=20),
        ),
    ]
