# Generated by Django 6.0.4 on 2026-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_candidat_date_inscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='statut_emploi',
            field=models.CharField(choices=[('ACTIVE', 'En poste'), ('TERMINATED', 'Contrat terminé'), ('LEFT', 'A quitté le poste')], default='ACTIVE', max_length=20),
        ),
    ]
