# Generated by Django 6.0.4 on 2026-05-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_placement_statut_emploi'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire (Candidat)'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observations (Admin)'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='statut',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('PLACED', 'Placé'), ('WAITING', 'En attente'), ('REFUSED', 'Refusé')], db_index=True, default='AVAILABLE', max_length=20),
        ),
    ]
