# Generated by Django 6.0.4 on 2026-05-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_candidat_commentaire_alter_candidat_observations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrequest',
            name='est_traitee',
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='statut',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('REFUSED', 'Refusée')], default='PENDING', max_length=20),
        ),
    ]
