# Generated by Django 5.1.3 on 2026-05-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0017_alter_candidat_poste_recherche_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidat",
            name="disponibilite",
            field=models.CharField(
                choices=[
                    ("JOURNALIER", "Journalier"),
                    ("DAILY", "Descend chaque jour"),
                    ("WEEKLY", "Descente chaque semaine"),
                    ("BI_WEEKLY", "Descend chaque 15 jours"),
                    ("LIVE_IN", "Logée"),
                    ("LIVE_OUT", "Non logée"),
                ],
                max_length=50,
            ),
        ),
    ]
