# Generated by Django 5.1.3 on 2026-05-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0018_alter_candidat_disponibilite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidat",
            name="certificat_medical",
        ),
        migrations.AddField(
            model_name="candidat",
            name="certificat_residence",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/residence/",
                verbose_name="Certificat de Résidence",
            ),
        ),
        migrations.AlterField(
            model_name="candidat",
            name="piece_identite",
            field=models.FileField(
                default="",
                upload_to="documents/cni/",
                verbose_name="Carte d'Identité (PDF/Image)",
            ),
            preserve_default=False,
        ),
    ]
