# Generated by Django 5.1.3 on 2026-05-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0019_remove_candidat_certificat_medical_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidat",
            name="frais_paye",
            field=models.BooleanField(
                default=False, verbose_name="Frais de dossier payés"
            ),
        ),
        migrations.AddField(
            model_name="candidat",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="ID Transaction Paiement",
            ),
        ),
        migrations.AlterField(
            model_name="candidat",
            name="photo",
            field=models.ImageField(default="", upload_to="candidats/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="candidat",
            name="statut",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Disponible"),
                    ("PLACED", "Placé"),
                    ("WAITING", "En attente"),
                    ("REFUSED", "Refusé"),
                    ("PAYMENT_PENDING", "En attente de paiement"),
                ],
                db_index=True,
                default="AVAILABLE",
                max_length=20,
            ),
        ),
    ]
